config/routes.rb
Rails.application.routes.draw do
  resources :moves
  resources :marks
get '/tutor', to: 'tutor#tutor' do
   erb :tutor, :locals => {:fen => params[:fen]}
end
  devise_for :users
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/grafo'

  resources :aulas
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aula.rb
class Aula < ApplicationRecord
 has_many :marks , dependent: :destroy
  accepts_nested_attributes_for :marks, allow_destroy: true, reject_if: :all_blank
 has_many :moves,dependent: :destroy
  accepts_nested_attributes_for :moves, allow_destroy: true, reject_if: proc { |attributes|  attributes['fen_esperado'].blank?}

 validates :nome, presence: true
 validates :conteudo, presence: true


 enum dificuldade: [:iniciante,:intermediario,:avançado]

end

app/controllers/aulas_controller.rb
class AulasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_aula, only: [:show, :edit, :update, :destroy]

  # GET /aulas
  # GET /aulas.json
  def index
    @aulas = Aula.all
  end

  # GET /aulas/1
  # GET /aulas/1.json
  def show
    gon.marks = @aula.marks.all
    gon.moves = @aula.moves.all
  end

  # GET /aulas/new
  def new
    @aula = Aula.new
    @aula.autor = current_user.nome
    @aula.marks.build
    @aula.moves.build
  end

  # GET /aulas/1/edit
  def edit
    @aula.marks.build
    @aula.moves.build
  end

  # POST /aulas
  # POST /aulas.json
  def create
    @aula = Aula.new(aula_params)

    respond_to do |format|
      if @aula.save
        format.html { redirect_to @aula, notice: 'Aula criada com sucesso.' }
        format.json { render :show, status: :created, location: @aula }
      else
        format.html { render :new }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aulas/1
  # PATCH/PUT /aulas/1.json
  def update
    respond_to do |format|
      if @aula.update(aula_params)
        format.html { redirect_to @aula, notice: 'Aula atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @aula }
      else
        format.html { render :edit }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aulas/1
  # DELETE /aulas/1.json
  def destroy
    @aula.destroy
    respond_to do |format|
      format.html { redirect_to aulas_url, notice: 'Aula apagada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aula
      @aula = Aula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aula_params
      params.require(:aula).permit(:nome, :conteudo, :fen,:autor,:jogador ,marks_attributes: Mark.attribute_names.map(&:to_sym).push(:_destroy),moves_attributes: Move.attribute_names.map(&:to_sym).push(:_destroy))
    end
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/views/aulas/_form.html.erb
<%= form_for @aula do |f| %>

  <% if aula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aula.errors.count, "error") %> prohibited this aula from being saved:</h2>

      <ul>
      <% aula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome %>
    <%= f.text_field :nome ,class:'form-control' %>

  </div>

  <div class="form-group">
    <label>Nível necessário para acessar a aula</label>

    <%= f.text_field :dificuldade , class: 'form-control' %>


  </div>


  <div class="form-group">
    <%= f.label :conteudo %>
    <%= f.text_area :conteudo, rows:2 ,class:'form-control'%>
  </div>

    <div class="form-group">
      <label>O aluno jogará com:</label>
      <%= f.select :jogador , options_for_select( [['branco','w'],['preto','b']], :selected => :jogador),{} ,{:class => "form-control"} %>
    </div>

  <div class="media">
    <div class="media-middle">
        <%= f.hidden_field :fen %>
        <div id="board" style="width: 25%; float: left;"></div>
    </div>
  </div>

<div class="form-group">
    <div id = "set_start_position" class="btn btn-primary"> Posicao inicial</div>
    <div id = "clear_board" class="btn btn-danger"> Limpar tabuleiro</div>

</div>
  <h2>Quadros que serão marcados</h2>
      <table class="table">
        <thead>
          <tr>

            <th>Quadro</th>
            <th>Valor</th>
            <th>Cor</th>
            <th></th>
          </tr>
        </thead>

        <tbody class ="marks">
            <%= f.fields_for :marks do |builder| %>
              <%= render 'mark', f: builder %>
            <%end%>

        </tbody>
      </table>
    <%= link_to_add_row('Adicionar Marcação', f, :marks, class: 'btn btn-primary') %>

<h2>Movimentos</h2>
<table class="table">
  <thead>
    <tr>

    <th>movimento esperado </th>
    <th>movimento do computador </th>
    <th> Movimento resultado</th>
    <th>pontos </th>

    <th>mensagem </th>
    <th>Fim</th>
    <th></th>

    </tr>
  </thead>
  <tbody class='moves'>
    <%=f.fields_for :moves do |move| %>
      <%= render 'move',f:move %>
    <%end%>
  </tbody>
</table>
    <%= link_to_add_row('Adicionar Movimento', f , :moves , class: 'btn btn-primary') %>
<br>

<div class = "col-xs-12">
    <%= f.submit("Criar Aula",class: 'btn btn-primary') %>
</div>

<% end %>
  
  <script type="text/javascript">



    ///
    var onChange= function(oldPos, newPos) {      
      $("input[name='aula[fen]']").val(ChessBoard.objToFen(newPos));

//      if(tables_computador[0].fen() == "8/8/8/8/8/8/8/8"){
          tables_esperado[0].position(ChessBoard.objToFen(newPos));
//      }
    };



    var position = $("input[name='aula[fen]']").val();

    var cfg= {
      position : position,
      draggable : true,
      sparePieces : true,
      dropOffBoard: 'trash',
      onChange : onChange
    };
    var board = ChessBoard('board',cfg);
    $(window).resize(board.resize);
    /// atributos dos botões
    $('#set_start_position').on('click', board.start);
    $('#clear_board').on('click', board.clear);
    
  </script>

app/views/aulas/_mark.html.erb
<tr>

  <td><%= f.text_field :quadro, label: false,class:'form-control' %></td>
  <td><%= f.text_field :valor, label: false,class:'form-control' %></td>
  <td><%= f.select :cor,[['Vermelho','red'],['Amarelo','yellow'],['Azul','blue']],{:include_blank => ''},class:'form-control'%></td>
  <td>
    <%= f.hidden_field :_destroy, as: :hidden %>
    <%= link_to 'Delete', '#', class: 'remove_record btn btn-danger' %>
  </td>
</tr>

app/views/aulas/_move.html.erb
<tr>



<td><%= f.hidden_field :fen_esperado, label: false ,class:'form-control' %>
    <div id="board_esperado_<%= f.object.__id__ %>" style ="width: 200px;" ></div>
  <div id = "clear_board_esperado_<%=f.object.__id__ %>" class="btn btn-danger"> Limpa </div>
  </td>

  <td><%= f.hidden_field :fen_computador, label: false,class:'form-control' %>
        <div id="board_computador_<%= f.object.__id__ %>" style ="width: 200px;" ></div>
      <div id = "clear_board_computador_<%=f.object.__id__ %>" class="btn btn-danger"> Limpa </div>
  </td>
  <td><%= f.hidden_field :fen_resultado, label: false,class:'form-control' %>
        <div id="board_resultado_<%= f.object.__id__ %>" style ="width: 200px;" ></div>
    <div id = "clear_board_resultado_<%=f.object.__id__ %>" class="btn btn-danger"> Limpa </div>
  </td>
  <td><%= f.text_field :pontos, label: false ,class:'form-control' %></td>

  <td><%= f.text_field :mensagem, label: false ,class:'form-control' %></td>
  <td>
      <%= f.check_box :final    %>

  </td>

  <td>
    <%= f.hidden_field :_destroy%>
    <%= link_to 'Apagar', '#', class: 'remove_record btn btn-danger' %>

  </td>
  <td>
    <div class="btn btn-default" id="copia_<%=f.object.__id__%>"> Copia anterior</div>
    <div class="btn btn-primary" id="copia_primeiro_<%=f.object.__id__%>"> Copia primeiro</div>


  </td>
</tr>


<script>





    /*****************Board_ do movimento esperado****************/
    
    
    var onDrop_esperado = function(source, target, piece, newPos, oldPos, orientation) {
        board_computador_<%=f.object.__id__ %>.position(ChessBoard.objToFen(newPos));
    };

        /**Atualiza o valor no objeto**/
     var onChange_esperado = function(oldPos, newPos) {
        $("#board_esperado_<%=f.object.__id__ %>").prev('input[type=hidden]').val(ChessBoard.objToFen(newPos));
    };

        /**Posicao para inicializacao (no caso da edicao**/
    var posicao_esperado = $("#board_esperado_<%=f.object.__id__ %>").prev('input[type=hidden]').val();
    
    var cfg_esperado= {
        position : posicao_esperado,
        draggable : true,
        dropOffBoard: 'snapback',
        onChange : onChange_esperado,
        onDrop :onDrop_esperado
    };

    var board_esperado_<%=f.object.__id__ %> = ChessBoard("board_esperado_<%=f.object.__id__ %>",cfg_esperado);
    $(window).resize(board_esperado_<%=f.object.__id__ %>.resize);
    tables_esperado.push(board_esperado_<%=f.object.__id__ %>);

    /*******************/



    /***********Board Movimento resultante********/
    /*Atualiza o proximo quadro*/
    var onDrop_resultado = function(source, target, piece, newPos, oldPos, orientation) {
        var my_index =tables_esperado.indexOf(board_esperado_<%= f.object.__id__ %>);
        if(tables_esperado.length - 1 > my_index){
            tables_esperado[my_index + 1].position(ChessBoard.objToFen(newPos));
        }
    };


        /**Atualiza o valor no objeto**/
     var onChange_resultado = function(oldPos, newPos) {
        $("#board_resultado_<%=f.object.__id__ %>").prev('input[type=hidden]').val(ChessBoard.objToFen(newPos));
    };

        /**Posicao para inicializacao (no caso da edicao**/
    var posicao_resultado = $("#board_resultado_<%=f.object.__id__ %>").prev('input[type=hidden]').val();

    var cfg_resultado= {
        position : posicao_resultado,
        draggable : true,
        dropOffBoard: 'snapback',
        onChange : onChange_resultado,
        onDrop : onDrop_resultado
    };

    var board_resultado_<%=f.object.__id__ %> = ChessBoard("board_resultado_<%=f.object.__id__ %>",cfg_resultado);
    $(window).resize(board_resultado_<%=f.object.__id__ %>.resize);
    tables_resultado.push(board_resultado_<%=f.object.__id__ %>);



    /*************Board movimento do computador*********/
    
    var onChange_computador = function(oldPos, newPos) {
        $("#board_computador_<%= f.object.__id__ %>").prev('input[type=hidden]').val(ChessBoard.objToFen(newPos));
    };
   

    var onDrop_computador = function(source, target, piece, newPos, oldPos, orientation) {
        board_resultado_<%=f.object.__id__ %>.position(ChessBoard.objToFen(newPos));
    };

    var posicao_computador = $("#board_computador_<%= f.object.__id__ %>").prev('input[type=hidden]').val();

    var cfg_computador= {
        position : posicao_computador,
        draggable : true,
        dropOffBoard: 'snapback',
        onChange : onChange_computador,
        onDrop : onDrop_computador
    };


    var board_computador_<%= f.object.__id__ %> = ChessBoard("board_computador_<%= f.object.__id__ %>",cfg_computador);
    $(window).resize(board_computador_<%= f.object.__id__ %> .resize);
    tables_computador.push(board_computador_<%= f.object.__id__ %>);
    /*******************/



    /***********Board Movimento resultante********/
    $('#copia_<%=f.object.__id__%>').on('click', function(){
        var my_index =tables_esperado.indexOf(board_esperado_<%= f.object.__id__ %>);
        if(my_index >0){
            board_esperado_<%= f.object.__id__ %>.position(tables_esperado[my_index-1].fen());
            board_computador_<%= f.object.__id__ %>.position(tables_computador[my_index-1].fen());
        }
    });
    $('#copia_primeiro_<%=f.object.__id__%>').on('click', function(){
        var my_index =tables_esperado.indexOf(board_esperado_<%= f.object.__id__ %>);
        if(my_index >0){
            board_esperado_<%= f.object.__id__ %>.position(tables_esperado[0].fen());
            board_computador_<%= f.object.__id__ %>.position(tables_computador[0].fen());
        }
    });

    $('#clear_board_esperado_<%=f.object.__id__ %>').on('click', board_esperado_<%=f.object.__id__ %>.clear);
    $('#clear_board_computador_<%=f.object.__id__ %>').on('click', board_computador_<%=f.object.__id__ %>.clear);
    $('#clear_board_resultado_<%=f.object.__id__ %>').on('click', board_resultado_<%=f.object.__id__ %>.clear);



</script>

app/views/aulas/edit.html.erb
<h1>Editar Aula</h1>

<%= render 'form', aula: @aula %>

<%= link_to 'Show', @aula %> |
<%= link_to 'Back', aulas_path %>

app/views/aulas/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-xs-12">
  <h1>Aulas</h1>
</div>
<div class="row">

  <div class="col-xs-12">Bem Vindo à nossas aulas, sinta-se a vontade para explorar</div>

</div>
  <div class="table-responsive ">
    <table class="table table-hover">
      <thead>
        <tr>
          <th colspan="2"></th>
          <th >Nome</th>
          <th>Conteudo</th>
          <th>Dificuldade</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @aulas.each do |aula| %>
          <tr>
            <td colspan="2"></td>
            <td><%= aula.nome %></td>
            <td> <%= aula.conteudo %></td>
            <td><%= aula.dificuldade %></td>
            <td><%= link_to 'Começar a aula', aula ,class:'btn btn-primary' %></td>
            <td><%= link_to 'Editar Aula', edit_aula_path(aula) , class:'btn btn-warning' %></td>
            <td><%= link_to 'Apagar', aula, method: :delete, data: { confirm: 'Tem certeza?' } , class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
</table>
  </div>
<br>



<%= link_to 'New Aula', new_aula_path , class: 'btn btn-primary' %>

app/views/aulas/new.html.erb
<h1>Criar Aula</h1>

<%= render 'form', aula: @aula %>

<%= link_to 'Back', aulas_path,class: 'btn btn-default' %>

app/views/aulas/show.html.erb
<head> 
<script src="../assets/chessboard-0.3.0.min.js"></script>
</head>


<p id="notice"><%= notice %></p>

<div class="panel-body">
  <div class="row">
    <strong>Autor:</strong>
    <%= @aula.autor %>
  </div>
  <div class="row">
  <strong>Nome:</strong>
  <%= @aula.nome %>
  </div>

<div class="row">
  <strong>Conteudo:</strong>
  <%= @aula.conteudo %>
</div>
</div>


<div id="divFen" style="display: none;"><%= @aula.fen %></div>

<div class="row" style="padding-bottom: 50px">
  <div class="col-xs-6 center-block">
    <div id="board" style="width: 65%"></div>
  </div>


  <div class="col-xs-6 " >
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">

            <li ><a id ="mensagem"></a></li>
          </ul>
        </div>

      </div>
    </nav>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">

            <li><a id="voltar">Movimento Anterior</a></li>
          </ul>
        </div>

      </div>
    </nav>
  </div>
</div>



<div class="ui-button">
  <%= link_to 'Editar', edit_aula_path(@aula) , class: "btn btn-warning" %>
  <%= link_to 'Voltar', aulas_path, class: "btn btn-danger" %>
</div>
<script type="text/javascript">

    var posicao = $("#divFen").text() +' <%=@aula.jogador%> - - 0 1';

    var move_atual;
    var indice_atual =0;
    var historico_movimentos = [];

    var game;

    var onDragStart = function(source, piece) {
        // do not pick up pieces if the game is over
        // or if it's not that side's turn
        if (game.game_over() === true ||
            (game.turn() === 'w' && piece.search(/^b/) !== -1) ||
            (game.turn() === 'b' && piece.search(/^w/) !== -1)||
              move_atual.final) {
            return false;
        }
    };

    var onDrop = function(source, target) {
        removeGreySquares();

        // see if the move is legal
        var move = game.move({
            from: source,
            to: target,
            promotion: 'q' // NOTE: always promote to a queen for example simplicity
        });

        // illegal move
        if (move === null) return 'snapback';
    };

    var onMouseoverSquare = function(square, piece) {
        // get list of possible moves for this square
        if(move_atual.final) return;
        var moves = game.moves({
            square: square,
            verbose: true
        });
        if (moves.length === 0) return;
        greySquare(square);
        for (var i = 0; i < moves.length; i++) {
            greySquare(moves[i].to);
        }
    };

    var onMouseoutSquare = function(square, piece) {
        removeGreySquares();
    };

    var onSnapEnd = function() {
        var achou = false;
        historico_movimentos.push(indice_atual);
        board.position(game.fen());
        achou = procura_proximo_movimento();
        if(achou) {
            movimenta_board(1000);
            if(procura_final()){
                game.set_game_over();


            }
        }


    };
    function procura_final(){
        var achou = false;
        $.each(gon.moves,function() {
            if(this.fen_esperado === board.fen() && this.final){
                achou = true;
                move_atual = gon.moves[indice_atual];
                $('#mensagem').text(move_atual.mensagem);
            }
        });
        return achou;

    }

    function procura_proximo_movimento(){
      var achou = false;
        $.each(gon.moves,function () {
            if(this.fen_esperado === board.fen()){
                achou = true;
                indice_atual = gon.moves.indexOf(this);
                move_atual = gon.moves[indice_atual];
                $('#mensagem').text(move_atual.mensagem);
                posicao = move_atual.fen_computador +' <%=@aula.jogador%> - - 0 1';

            }
        });
        return achou;
    }



    var cfg = {
        draggable: true,
        position: posicao,
        onDragStart: onDragStart,
        onDrop: onDrop,
        onMouseoutSquare: onMouseoutSquare,
        onMouseoverSquare: onMouseoverSquare,
        onSnapEnd: onSnapEnd
    };

    var removeGreySquares = function() {
        $('#board .square-55d63').css('background', '');
    };

    var greySquare = function(square) {
        var squareEl = $('#board .square-' + square);

        var background = '#a9a9a9';
        if (squareEl.hasClass('black-3c85d') === true) {
            background = '#696969';
        }

        squareEl.css('background', background);
    };
      /**Funcoes do jogo**/

      Inicia();


      function Inicia(){
          move_atual = gon.moves[indice_atual];
          board = ChessBoard('board', cfg);
          posicao = move_atual.fen_computador +' <%=@aula.jogador%> - - 0 1';
          game = new Chess(posicao);
          movimenta_board(2000);
      }


      function movimenta_board(timeout){

          setTimeout(function(){
              board.position(posicao);
              $('#mensagem').text(move_atual.mensagem);
              if( !game.load(posicao)) {
                  //alert("Aula com erro de configuração.");
              }
          }, timeout);
      }
      $("#voltar").on('click',function () {
          if(historico_movimentos.length > 0) {
              var ultimo_movimento = historico_movimentos.pop();
              move_atual = gon.moves[ultimo_movimento];
              posicao = move_atual.fen_computador + ' <%=@aula.jogador%> - - 0 1';
              game.load(posicao);
              board.position(posicao);
          }

      });












    /******************Marks*****************/
    var tamanho = board.squareSize();


    $.each(gon.marks,function(){
		highlight(this.quadro,this.valor,this.cor);
	});


	function highlight(quadro,valor,cor){
	  var quadro = getQuadro(quadro);

	  if(quadro == null)return;	  
	  
	  quadro.append('<div style=\"font-size:'+tamanho/2+'px;color:'+cor+';padding-left:'+tamanho/3+'px; padding-top:'+tamanho/5+'px;position:absolute;\">'+valor+'</div>');  
	}

	function getQuadro(quadro){
		return $("div").find("[data-square='" + quadro + "']");
	}

  $(window).resize(board.resize);



	
</script>