config/routes.rb
Rails.application.routes.draw do
  resources :moves
  resources :marks
get '/tutor', to: 'tutor#tutor' do
   erb :tutor, :locals => {:fen => params[:fen]}
end
  devise_for :users
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/grafo'

  resources :aulas
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/move.rb
class Move < ApplicationRecord
  belongs_to :aula,optional: true
  has_ancestry
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]

  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
  end

  # GET /moves/new
  def new
    @move = Move.new
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to @move, notice: 'Move was successfully created.' }
        format.json { render :show, status: :created, location: @move }
      else
        format.html { render :new }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1
  # PATCH/PUT /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to @move, notice: 'Move was successfully updated.' }
        format.json { render :show, status: :ok, location: @move }
      else
        format.html { render :edit }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to moves_url, notice: 'Move was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def move_params
      params.require(:move).permit(:from, :to, :aula_id)
    end
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/_form.html.slim
= form_for @move do |f|
  - if @move.errors.any?
    #error_explanation
      h2 = "#{pluralize(@move.errors.count, "error")} prohibited this move from being saved:"
      ul
        - @move.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :from
    = f.text_area :from
  .field
    = f.label :to
    = f.text_field :to
  .field
    = f.label :aula
    = f.text_field :aula
  .actions = f.submit

app/views/moves/edit.html.slim
h1 Editing move

== render 'form'

= link_to 'Show', @move
'  |
= link_to 'Back', moves_path

app/views/moves/index.html.slim
h1 Listing moves

table
  thead
    tr
      th From
      th To
      th Aula
      th
      th
      th

  tbody
    - @moves.each do |move|
      tr
        td = move.from
        td = move.to
        td = move.aula
        td = link_to 'Show', move
        td = link_to 'Edit', edit_move_path(move)
        td = link_to 'Destroy', move, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Move', new_move_path

app/views/moves/new.html.slim
h1 New move

== render 'form'

= link_to 'Back', moves_path

app/views/moves/show.html.slim
p#notice = notice

p
  strong From:
  = @move.from
p
  strong To:
  = @move.to
p
  strong Aula:
  = @move.aula

= link_to 'Edit', edit_move_path(@move)
'  |
= link_to 'Back', moves_path